package com.sun.entity;
// Generated 2017/6/15  10:38:54 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SunBatch generated by hbm2java
 */
@Entity
@Table(name = "sun_batch", catalog = "model_practice")
public class SunBatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6250605561419744155L;
	
	private String id;
	private String description;
	private String cronStr;
	private Date runTime;
	private Date updateTime;

	public SunBatch() {
	}

	public SunBatch(String id, String description, String cronStr, Date runTime, Date updateTime) {
		this.id = id;
		this.description = description;
		this.cronStr = cronStr;
		this.runTime = runTime;
		this.updateTime = updateTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cron_str", nullable = false, length = 50)
	public String getCronStr() {
		return this.cronStr;
	}

	public void setCronStr(String cronStr) {
		this.cronStr = cronStr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "run_time", nullable = false, length = 19)
	public Date getRunTime() {
		return this.runTime;
	}

	public void setRunTime(Date runTime) {
		this.runTime = runTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
